### ISSUE TITLE
Connected status of client?

### ISSUE THREAD

**Issue by chainhead** [mqttjs/async-mqtt#13]
How do I get the [connection status](https://github.com/mqttjs/MQTT.js#mqttclientconnected) of a client? The following returns `undefined`.

```
const MQTT = require('async-mqtt')
const uuidv1 = require('uuid/v1')
//
var client = MQTT.connect('tcp://localhost:1883', { clientId: uuidv1() })
client.on('connect', () => {
    console.log(client.connected)
})
client.on('reconnect', () => {
    console.log('Reconnected.')
})
client.on('close', () => {
    console.log('Closed.')
})
```

This `client._client.connected` returns `true`, however.

**Comment by RangerMauve** [comment]
Snap! That's 100% a bug. I'll add something for it sometime soon.

In the meantime, a pr that extends from #11 would be very much welcome. We just need to add a new getter for the connected status and add a unit test to check for it.
