### ISSUE TITLE
Missing type script declaration file in npm repository

### ISSUE THREAD

**Issue by Ni-vek** [mqttjs/async-mqtt#14]
Am I crazy or this file is missing?

**Comment by RangerMauve** [comment]
Sorry! I got stalled by needing to test #11

Do you think you'd have time to check if that PR works?

**Comment by bernardobelchior** [comment]
Any news on this? I'm starting a new project and TS types would be very useful :smiley:

**Comment by Ni-vek** [comment]
Yes that PR is OK!

**Comment by RangerMauve** [comment]
Cool, I've released the new version along with the typescript files in 2.2.0
