### ISSUE TITLE
client.off() doesn't exit on MqttClient when connectAsync()

### ISSUE THREAD

**Issue by miguelrodlav** [mqttjs/async-mqtt#22]
When you try execute `connectAsync()`, the `removePromiseResolutionListeners()` function try to execute:

`client.off(eventName, promiseResolutionListeners[eventName]);`

And this `client.off` function doesn't exists on the `MqttClient.propotype`

So this `connectAsync` function crash.

Shouldn't it be `removeListener` instead of `off`?

**Comment by RangerMauve** [comment]
On dang, you're right it should be `removeListener()`. I don't have much bandwidth to add to this, so a PR that addresses this would be very much welcome. 💜

**Comment by miguelrodlav** [comment]
No problem!! Done!!

**Comment by RangerMauve** [comment]
Fixed by #24

Released in v2.4.1

Thank you!
