### ISSUE TITLE
Client.stream is undefined

### ISSUE THREAD

**Issue by 7Surfer** [mqttjs/async-mqtt#28]
Hey,
i tried to check if the connection is established. So in the synchronous MQTT there is a way with 

`const mqtt = require('async-mqtt);`
`client = mqtt.connect(adress);`
`client.stream.on('error',/*error handler*/);`

To check the stream. But when i try the same in the async i only get a error tath the stream is undefiened.

**Comment by RangerMauve** [comment]
Is there a particular reason you can't use `client.on('connect')` to listen for when the connection is established?

**Comment by 7Surfer** [comment]
Maybe i wrote it unclear.
The problem i have is, that i want to check if the connection failed. (for a unit test)
The `client.on('error,function())` does not get called so i don't get any error on this failed connection.
With the sync mqtt i could get the error by the stream property but when i try i get a undefined error.


Here's the code where i get the error:
`client = await mqtt.connectAsync({`
`      host: this.config.mqttConnector.host,`
`      port: this.config.mqttConnector.port,`
`      protocol: 'mqtt://'`
`    });`
`this.client.stream.on('error', () => throw new Error('Connection failed'));`

Error:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined`

**Comment by RangerMauve** [comment]
Ah! Thank you for the details! I think the problem is that we aren't passing all the events from the mqtt.js client to the async client! I'll submit a patch and see if that helps. (you should be able to get the `client.on('error'` code then)

**Comment by RangerMauve** [comment]
Err, nevermind, invoking `client.on('error')` should be working. Do any of the `client.on` events work?

**Comment by RangerMauve** [comment]
I don't think client.stream is a standard property since it's not in the docs, would you be comfortable with using `client._client.stream` for now?

**Comment by 7Surfer** [comment]
> Err, nevermind, invoking `client.on('error')` should be working. Do any of the `client.on` events work?

The `client.on('message')`, and `close` are woking fine for me.



> I don't think client.stream is a standard property since it's not in the docs, would you be comfortable with using `client._client.stream` for now?

Unfortunately i can't check if `client._client.stream` is working for me but if it does, it would be great. I can check it tomorrow and let you know. Thanks

**Comment by 7Surfer** [comment]
First of all thanks for the help, the `client._client.stream` is working fine.
So I think the Issue should be closed.

But the bad news is, the `connectAsync` is stuck in the connecting phase and not returning. But that problem may be a other issue.
