### ISSUE TITLE
How to get message from mqtt in async way?

### ISSUE THREAD

**Issue by iriekun** [mqttjs/async-mqtt#29]
Hi! how can I get message from mqtt in asynchronous way?

**Comment by burritoIand** [comment]
did you figure this out? what'd you do?

**Comment by RangerMauve** [comment]
You can check out the recent addition of `EventEmitter.on` to [node.js](https://github.com/nodejs/node/commit/eb8268353829729374e9cf2a1e149b467a4611d3) which turns events in an event emtitter into async iterators.
