### ISSUE TITLE
publish options not working

### ISSUE THREAD

**Issue by brambex** [mqttjs/async-mqtt#36]
Hi,

It seems like the publish options aren't working:
```
const options = { retain: true, qos: 1, dup: false };
client.publish(topic, JSON.stringify(message), options);
```

gives this as result in MQTT BOX
![image](https://user-images.githubusercontent.com/62907760/85033096-d83c9280-b180-11ea-93a1-dd5344187917.png)

as you can see retain: false and qos: 0

**Comment by brambex** [comment]
Bug found. Mqtt endpoint was a proxy, messing thing up...

**Comment by beavis88** [comment]
Retain still not working
