### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by burritoIand** [mqttjs/async-mqtt#37]
Hey just wondering if we can get a new release with the latest v4.1.0 of mqtt? The latest release is behind and using 2.5.0, it'd be nice if they were in sync.

Thanks!

**Comment by RangerMauve** [comment]
Oh, great idea.

Would you down to submit a PR for the update and check that the tests are passing? :o

**Comment by burritoIand** [comment]
@RangerMauve master is already updated to 4.1.0, it just need a release

**Comment by RangerMauve** [comment]
Oh, thanks for the heads up. Just released 2.6.1. 😁
