### ISSUE TITLE
Promise based RPC feature discussion

### ISSUE THREAD

**Issue by cameronelliott** [mqttjs/async-mqtt#39]
I am really excited about this library, and there is one or two features I would like to discuss with the maintainers.

The main feature is JSON based RPC, this allows request/response type messaging to be used with promises.

This isn't my idea, it comes from here:
[RPC for async Websockets library](https://github.com/vitalets/websocket-as-promised#sending-requests)
(with thanks to Vitalets for such a brilliant idea!)

> 
> ## JSON RPC Feature found in 
> *websocket-as-promised* provides simple request-response mechanism ([JSON RPC](https://www.jsonrpc.org)). 
> Method `.sendRequest()` sends message with unique `requestId` and returns promise. 
> That promise get resolved when response message with the same `requestId` comes. 
> For reading/setting `requestId` from/to message there are two functions defined in options `attachRequestId / extractRequestId`:
> ```js
> const wsp = new WebSocketAsPromised(wsUrl, {
>   packMessage: data => JSON.stringify(data),
>   unpackMessage: data => JSON.parse(data),
>   attachRequestId: (data, requestId) => Object.assign({id: requestId}, data), // attach requestId to message as `id` field
>   extractRequestId: data => data && data.id,                                  // read requestId from message `id` field
> });
> 
> wsp.open()
>  .then(() => wsp.sendRequest({foo: 'bar'})) // actually sends {foo: 'bar', id: 'xxx'}, because `attachRequestId` defined above
>  .then(response => console.log(response));  // waits server message with corresponding requestId: {id: 'xxx', ...}
> ```
> By default `requestId` value is auto-generated, but you can set it manually:
> ```js
> wsp.sendRequest({foo: 'bar'}, {requestId: 42});
> ```

I will take a stab at implementing this, but I would also invite more experienced JS developers to speak up if they would like to implement it!

**Comment by cameronelliott** [comment]
I would also like feedback from the maintainers if they would be interested in a PR for this feature?

**Comment by cameronelliott** [comment]
I am closing/withdrawing this issue.
I have made changes which get me close to this approach here:
https://github.com/x186k/async-mqtt-x186k
If the maintainers would like to discuss a PR, I would be thrilled!

**Comment by RangerMauve** [comment]
Hey! THank you for opening up this issue. I think the RPC idea is really cool, but it feels like it'd be better as a module built on top of async-mqtt.

I'd be happy to point people towards such a library in the README so that people that could have use from it will find it easier.
