### ISSUE TITLE
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex

### ISSUE THREAD

**Issue by neilenns** [mqttjs/async-mqtt#50]
Dependabot is throwing an error in my project from async-mqtt due to a security vunlerability in a dependency:

> async-mqtt@2.6.1 requires glob-parent@^3.1.0 via a transitive dependency on glob-stream@6.1.0

> The earliest fixed version is 5.1.2.

**Comment by RangerMauve** [comment]
Is this coming from the `mqtt` dependency? Any chance you could submit a PR to fix it?

**Comment by neilenns** [comment]
It appears to be from `eslint`! Rolling to the last 7.x release appears to bump glob-parent to a min of `5.1.2`. PR incoming shortly.

**Comment by RangerMauve** [comment]
should be fixed in 2.6.3
