### ISSUE TITLE
MQTT with TLS enabled causes a ECONNRESET when issuing await client.end()

### ISSUE THREAD

**Issue by davidkjackson54** [mqttjs/async-mqtt#52]
Issuing an 
await client.publish immediately followed by 
await client,.end() results in:
the client.on(error) function to be triggered which reports:
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)

If I revert back to non tls using port 1883 then it works fine to completion.

Running  Windows 10 Enterprise
Node.js 16.15.0
mosquitto 2.0.14

**Comment by RangerMauve** [comment]
Not sure what to do about this. Is it related to QoS or the callback passed to publish not actually being used? Does doing `client.end()` in other circumstances throw the error?
